export const BASE_URL = 'https://api.nytimes.com/'
export const BASE_ENDPOINT = 'svc/search/v2/'
export const ARTICLE_SEARCH = 'articlesearch.json'
export const API_KEY = 'pdiRET3l7Osnyk7IHvSPl0ziiWFCFly1'
export const QUERY_KEYWORD = 'Science'
export const IMAGE_ENDPOINT = 'https://static01.nyt.com/'